# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\iwsk.ui'
#
# Created: Sat Mar 17 20:17:03 2012
#      by: PyQt4 UI code generator 4.9
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(436, 454)
        Dialog.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.gridLayout_2 = QtGui.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 0, 0, 1, 1)
        self.o_recived_plainTextEdit = QtGui.QPlainTextEdit(self.tab)
        self.o_recived_plainTextEdit.setEnabled(True)
        self.o_recived_plainTextEdit.setPlainText(_fromUtf8(""))
        self.o_recived_plainTextEdit.setObjectName(_fromUtf8("o_recived_plainTextEdit"))
        self.gridLayout_4.addWidget(self.o_recived_plainTextEdit, 1, 0, 1, 3)
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_4.addWidget(self.label_9, 2, 0, 1, 1)
        self.o_send_plainTextEdit = QtGui.QPlainTextEdit(self.tab)
        self.o_send_plainTextEdit.setObjectName(_fromUtf8("o_send_plainTextEdit"))
        self.gridLayout_4.addWidget(self.o_send_plainTextEdit, 3, 0, 1, 3)
        self.btn_pingFunction = QtGui.QPushButton(self.tab)
        self.btn_pingFunction.setObjectName(_fromUtf8("btn_pingFunction"))
        self.gridLayout_4.addWidget(self.btn_pingFunction, 4, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.tab)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_4.addWidget(self.label_10, 4, 1, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.tab)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout_4.addWidget(self.lineEdit, 4, 2, 1, 1)
        self.btn_send = QtGui.QPushButton(self.tab)
        self.btn_send.setObjectName(_fromUtf8("btn_send"))
        self.gridLayout_4.addWidget(self.btn_send, 4, 3, 1, 1)
        self.btn_clear_send = QtGui.QPushButton(self.tab)
        self.btn_clear_send.setObjectName(_fromUtf8("btn_clear_send"))
        self.gridLayout_4.addWidget(self.btn_clear_send, 3, 3, 1, 1)
        self.btn_clear_recived = QtGui.QPushButton(self.tab)
        self.btn_clear_recived.setObjectName(_fromUtf8("btn_clear_recived"))
        self.gridLayout_4.addWidget(self.btn_clear_recived, 1, 3, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.btn_open = QtGui.QPushButton(self.tab)
        self.btn_open.setObjectName(_fromUtf8("btn_open"))
        self.horizontalLayout_4.addWidget(self.btn_open)
        self.btn_close = QtGui.QPushButton(self.tab)
        self.btn_close.setObjectName(_fromUtf8("btn_close"))
        self.horizontalLayout_4.addWidget(self.btn_close)
        self.gridLayout_4.addLayout(self.horizontalLayout_4, 5, 0, 1, 4)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label = QtGui.QLabel(self.tab_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.i_portName_comboBox = QtGui.QComboBox(self.tab_2)
        self.i_portName_comboBox.setObjectName(_fromUtf8("i_portName_comboBox"))
        self.gridLayout_3.addWidget(self.i_portName_comboBox, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.i_baudRate_comboBox = QtGui.QComboBox(self.tab_2)
        self.i_baudRate_comboBox.setObjectName(_fromUtf8("i_baudRate_comboBox"))
        self.gridLayout_3.addWidget(self.i_baudRate_comboBox, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.tab_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.i_word_5bits_radio = QtGui.QRadioButton(self.groupBox_2)
        self.i_word_5bits_radio.setObjectName(_fromUtf8("i_word_5bits_radio"))
        self.horizontalLayout.addWidget(self.i_word_5bits_radio)
        self.i_word_6bits_radio = QtGui.QRadioButton(self.groupBox_2)
        self.i_word_6bits_radio.setObjectName(_fromUtf8("i_word_6bits_radio"))
        self.horizontalLayout.addWidget(self.i_word_6bits_radio)
        self.i_word_7bits_radio = QtGui.QRadioButton(self.groupBox_2)
        self.i_word_7bits_radio.setObjectName(_fromUtf8("i_word_7bits_radio"))
        self.horizontalLayout.addWidget(self.i_word_7bits_radio)
        self.i_word_8bits_radio = QtGui.QRadioButton(self.groupBox_2)
        self.i_word_8bits_radio.setObjectName(_fromUtf8("i_word_8bits_radio"))
        self.horizontalLayout.addWidget(self.i_word_8bits_radio)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout_3.addWidget(self.groupBox_2, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.tab_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 3, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.i_parityNone_radio = QtGui.QRadioButton(self.groupBox_3)
        self.i_parityNone_radio.setObjectName(_fromUtf8("i_parityNone_radio"))
        self.horizontalLayout_2.addWidget(self.i_parityNone_radio)
        self.i_parityEven_radio = QtGui.QRadioButton(self.groupBox_3)
        self.i_parityEven_radio.setObjectName(_fromUtf8("i_parityEven_radio"))
        self.horizontalLayout_2.addWidget(self.i_parityEven_radio)
        self.i_parityOdd_radio = QtGui.QRadioButton(self.groupBox_3)
        self.i_parityOdd_radio.setObjectName(_fromUtf8("i_parityOdd_radio"))
        self.horizontalLayout_2.addWidget(self.i_parityOdd_radio)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.gridLayout_3.addWidget(self.groupBox_3, 3, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 4, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_4.setTitle(_fromUtf8(""))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.i_stopBit1_radio = QtGui.QRadioButton(self.groupBox_4)
        self.i_stopBit1_radio.setObjectName(_fromUtf8("i_stopBit1_radio"))
        self.horizontalLayout_3.addWidget(self.i_stopBit1_radio)
        self.i_stopBit15_radio = QtGui.QRadioButton(self.groupBox_4)
        self.i_stopBit15_radio.setObjectName(_fromUtf8("i_stopBit15_radio"))
        self.horizontalLayout_3.addWidget(self.i_stopBit15_radio)
        self.i_stopBit2_radio = QtGui.QRadioButton(self.groupBox_4)
        self.i_stopBit2_radio.setObjectName(_fromUtf8("i_stopBit2_radio"))
        self.horizontalLayout_3.addWidget(self.i_stopBit2_radio)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_3)
        self.gridLayout_3.addWidget(self.groupBox_4, 4, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.tab_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 5, 0, 1, 1)
        self.i_protocol_comboBox = QtGui.QComboBox(self.tab_2)
        self.i_protocol_comboBox.setObjectName(_fromUtf8("i_protocol_comboBox"))
        self.gridLayout_3.addWidget(self.i_protocol_comboBox, 5, 1, 1, 1)
        self.i_terminator_comboBox = QtGui.QComboBox(self.tab_2)
        self.i_terminator_comboBox.setObjectName(_fromUtf8("i_terminator_comboBox"))
        self.gridLayout_3.addWidget(self.i_terminator_comboBox, 6, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.tab_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 6, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.tab_2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_3.addWidget(self.label_11, 10, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.i_timeout_spinBox = QtGui.QSpinBox(self.tab_2)
        self.i_timeout_spinBox.setWrapping(False)
        self.i_timeout_spinBox.setFrame(True)
        self.i_timeout_spinBox.setReadOnly(False)
        self.i_timeout_spinBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.i_timeout_spinBox.setMaximum(999999)
        self.i_timeout_spinBox.setSingleStep(1)
        self.i_timeout_spinBox.setObjectName(_fromUtf8("i_timeout_spinBox"))
        self.horizontalLayout_6.addWidget(self.i_timeout_spinBox)
        self.label_12 = QtGui.QLabel(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_6.addWidget(self.label_12)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 10, 1, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(20)
        self.horizontalLayout_7.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.horizontalLayout_7.setContentsMargins(-1, -1, 30, -1)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.i_howMuchChars_spinBox = QtGui.QSpinBox(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.i_howMuchChars_spinBox.sizePolicy().hasHeightForWidth())
        self.i_howMuchChars_spinBox.setSizePolicy(sizePolicy)
        self.i_howMuchChars_spinBox.setMinimum(1)
        self.i_howMuchChars_spinBox.setMaximum(2)
        self.i_howMuchChars_spinBox.setObjectName(_fromUtf8("i_howMuchChars_spinBox"))
        self.horizontalLayout_7.addWidget(self.i_howMuchChars_spinBox)
        self.i_itsTerminator_lineEdit = QtGui.QLineEdit(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.i_itsTerminator_lineEdit.sizePolicy().hasHeightForWidth())
        self.i_itsTerminator_lineEdit.setSizePolicy(sizePolicy)
        self.i_itsTerminator_lineEdit.setText(_fromUtf8(""))
        self.i_itsTerminator_lineEdit.setMaxLength(1)
        self.i_itsTerminator_lineEdit.setObjectName(_fromUtf8("i_itsTerminator_lineEdit"))
        self.horizontalLayout_7.addWidget(self.i_itsTerminator_lineEdit)
        self.gridLayout_3.addLayout(self.horizontalLayout_7, 8, 1, 1, 1)
        self.customTermator = QtGui.QLabel(self.tab_2)
        self.customTermator.setObjectName(_fromUtf8("customTermator"))
        self.gridLayout_3.addWidget(self.customTermator, 8, 0, 1, 1)
        self.i_automaticTerminator_checkBox = QtGui.QCheckBox(self.tab_2)
        self.i_automaticTerminator_checkBox.setChecked(True)
        self.i_automaticTerminator_checkBox.setObjectName(_fromUtf8("i_automaticTerminator_checkBox"))
        self.gridLayout_3.addWidget(self.i_automaticTerminator_checkBox, 9, 1, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.btn_save = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_save.sizePolicy().hasHeightForWidth())
        self.btn_save.setSizePolicy(sizePolicy)
        self.btn_save.setMinimumSize(QtCore.QSize(200, 35))
        self.btn_save.setObjectName(_fromUtf8("btn_save"))
        self.horizontalLayout_8.addWidget(self.btn_save)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 11, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabWidget, 0, 1, 1, 1)
        self.label_8.setBuddy(self.o_recived_plainTextEdit)
        self.label_9.setBuddy(self.o_send_plainTextEdit)
        self.label.setBuddy(self.i_portName_comboBox)
        self.label_2.setBuddy(self.i_baudRate_comboBox)
        self.label_3.setBuddy(self.i_word_5bits_radio)
        self.label_4.setBuddy(self.i_parityNone_radio)
        self.label_5.setBuddy(self.i_stopBit1_radio)
        self.label_6.setBuddy(self.i_protocol_comboBox)
        self.label_7.setBuddy(self.i_terminator_comboBox)
        self.label_11.setBuddy(self.i_timeout_spinBox)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.i_portName_comboBox, self.o_recived_plainTextEdit)
        Dialog.setTabOrder(self.o_recived_plainTextEdit, self.o_send_plainTextEdit)
        Dialog.setTabOrder(self.o_send_plainTextEdit, self.btn_pingFunction)
        Dialog.setTabOrder(self.btn_pingFunction, self.lineEdit)
        Dialog.setTabOrder(self.lineEdit, self.btn_send)
        Dialog.setTabOrder(self.btn_send, self.btn_clear_send)
        Dialog.setTabOrder(self.btn_clear_send, self.btn_clear_recived)
        Dialog.setTabOrder(self.btn_clear_recived, self.btn_open)
        Dialog.setTabOrder(self.btn_open, self.btn_close)
        Dialog.setTabOrder(self.btn_close, self.tabWidget)
        Dialog.setTabOrder(self.tabWidget, self.i_baudRate_comboBox)
        Dialog.setTabOrder(self.i_baudRate_comboBox, self.i_word_5bits_radio)
        Dialog.setTabOrder(self.i_word_5bits_radio, self.i_word_6bits_radio)
        Dialog.setTabOrder(self.i_word_6bits_radio, self.i_word_7bits_radio)
        Dialog.setTabOrder(self.i_word_7bits_radio, self.i_word_8bits_radio)
        Dialog.setTabOrder(self.i_word_8bits_radio, self.i_parityNone_radio)
        Dialog.setTabOrder(self.i_parityNone_radio, self.i_parityEven_radio)
        Dialog.setTabOrder(self.i_parityEven_radio, self.i_parityOdd_radio)
        Dialog.setTabOrder(self.i_parityOdd_radio, self.i_stopBit1_radio)
        Dialog.setTabOrder(self.i_stopBit1_radio, self.i_stopBit15_radio)
        Dialog.setTabOrder(self.i_stopBit15_radio, self.i_stopBit2_radio)
        Dialog.setTabOrder(self.i_stopBit2_radio, self.i_protocol_comboBox)
        Dialog.setTabOrder(self.i_protocol_comboBox, self.i_terminator_comboBox)
        Dialog.setTabOrder(self.i_terminator_comboBox, self.i_timeout_spinBox)
        Dialog.setTabOrder(self.i_timeout_spinBox, self.i_howMuchChars_spinBox)
        Dialog.setTabOrder(self.i_howMuchChars_spinBox, self.i_itsTerminator_lineEdit)
        Dialog.setTabOrder(self.i_itsTerminator_lineEdit, self.i_automaticTerminator_checkBox)
        Dialog.setTabOrder(self.i_automaticTerminator_checkBox, self.btn_save)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "IwSK RS-232", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Dane odebrane: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Dane wysłane:", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_pingFunction.setText(QtGui.QApplication.translate("Dialog", "PING!", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "Dane do wysłania:", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_send.setText(QtGui.QApplication.translate("Dialog", "Wyślij", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_clear_send.setText(QtGui.QApplication.translate("Dialog", "Wyczyść", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_clear_recived.setText(QtGui.QApplication.translate("Dialog", "Wyczyść", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_open.setText(QtGui.QApplication.translate("Dialog", "Otwórz port", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_close.setText(QtGui.QApplication.translate("Dialog", "Zamknij port", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Dialog", "Program", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Prędkość transmisji:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Długość słowa:", None, QtGui.QApplication.UnicodeUTF8))
        self.i_word_5bits_radio.setText(QtGui.QApplication.translate("Dialog", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.i_word_6bits_radio.setText(QtGui.QApplication.translate("Dialog", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.i_word_7bits_radio.setText(QtGui.QApplication.translate("Dialog", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.i_word_8bits_radio.setText(QtGui.QApplication.translate("Dialog", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Parzystość:", None, QtGui.QApplication.UnicodeUTF8))
        self.i_parityNone_radio.setText(QtGui.QApplication.translate("Dialog", "brak", None, QtGui.QApplication.UnicodeUTF8))
        self.i_parityEven_radio.setText(QtGui.QApplication.translate("Dialog", "bit parzystości", None, QtGui.QApplication.UnicodeUTF8))
        self.i_parityOdd_radio.setText(QtGui.QApplication.translate("Dialog", "bit nieparzystości", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Bit stopu:", None, QtGui.QApplication.UnicodeUTF8))
        self.i_stopBit1_radio.setText(QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.i_stopBit15_radio.setText(QtGui.QApplication.translate("Dialog", "1.5", None, QtGui.QApplication.UnicodeUTF8))
        self.i_stopBit2_radio.setText(QtGui.QApplication.translate("Dialog", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Kontrola przepływu:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Terminowanie:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "Timeout", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog", "[ms]", None, QtGui.QApplication.UnicodeUTF8))
        self.customTermator.setText(QtGui.QApplication.translate("Dialog", "Znaki: ", None, QtGui.QApplication.UnicodeUTF8))
        self.i_automaticTerminator_checkBox.setText(QtGui.QApplication.translate("Dialog", "automatycznie dołączaj terminator", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_save.setText(QtGui.QApplication.translate("Dialog", "Zapisz", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Dialog", "Konfiguracja", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

