# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\iwsk.ui'
#
# Created: Thu Mar 01 19:18:29 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(480, 640)
        Dialog.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.i_baudRate_comboBox = QtGui.QComboBox(self.groupBox)
        self.i_baudRate_comboBox.setObjectName(_fromUtf8("i_baudRate_comboBox"))
        self.gridLayout.addWidget(self.i_baudRate_comboBox, 1, 2, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.btn_save = QtGui.QPushButton(self.groupBox)
        self.btn_save.setObjectName(_fromUtf8("btn_save"))
        self.horizontalLayout_4.addWidget(self.btn_save)
        self.btn_open = QtGui.QPushButton(self.groupBox)
        self.btn_open.setObjectName(_fromUtf8("btn_open"))
        self.horizontalLayout_4.addWidget(self.btn_open)
        self.btn_close = QtGui.QPushButton(self.groupBox)
        self.btn_close.setObjectName(_fromUtf8("btn_close"))
        self.horizontalLayout_4.addWidget(self.btn_close)
        self.gridLayout.addLayout(self.horizontalLayout_4, 7, 0, 1, 3)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.comboBox_3 = QtGui.QComboBox(self.groupBox)
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.gridLayout.addWidget(self.comboBox_3, 5, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.comboBox_4 = QtGui.QComboBox(self.groupBox)
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.gridLayout.addWidget(self.comboBox_4, 6, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.i_portName_comboBox = QtGui.QComboBox(self.groupBox)
        self.i_portName_comboBox.setObjectName(_fromUtf8("i_portName_comboBox"))
        self.gridLayout.addWidget(self.i_portName_comboBox, 0, 2, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.i_word_5bits_radio = QtGui.QRadioButton(self.groupBox_2)
        self.i_word_5bits_radio.setObjectName(_fromUtf8("i_word_5bits_radio"))
        self.horizontalLayout.addWidget(self.i_word_5bits_radio)
        self.i_word_6bits_radio = QtGui.QRadioButton(self.groupBox_2)
        self.i_word_6bits_radio.setObjectName(_fromUtf8("i_word_6bits_radio"))
        self.horizontalLayout.addWidget(self.i_word_6bits_radio)
        self.i_word_7bits_radio = QtGui.QRadioButton(self.groupBox_2)
        self.i_word_7bits_radio.setObjectName(_fromUtf8("i_word_7bits_radio"))
        self.horizontalLayout.addWidget(self.i_word_7bits_radio)
        self.i_word_8bits_radio = QtGui.QRadioButton(self.groupBox_2)
        self.i_word_8bits_radio.setObjectName(_fromUtf8("i_word_8bits_radio"))
        self.horizontalLayout.addWidget(self.i_word_8bits_radio)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout.addWidget(self.groupBox_2, 2, 2, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.i_parityNone_radio = QtGui.QRadioButton(self.groupBox_3)
        self.i_parityNone_radio.setObjectName(_fromUtf8("i_parityNone_radio"))
        self.horizontalLayout_2.addWidget(self.i_parityNone_radio)
        self.i_parityEven_radio = QtGui.QRadioButton(self.groupBox_3)
        self.i_parityEven_radio.setObjectName(_fromUtf8("i_parityEven_radio"))
        self.horizontalLayout_2.addWidget(self.i_parityEven_radio)
        self.i_parityOdd_radio = QtGui.QRadioButton(self.groupBox_3)
        self.i_parityOdd_radio.setObjectName(_fromUtf8("i_parityOdd_radio"))
        self.horizontalLayout_2.addWidget(self.i_parityOdd_radio)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.gridLayout.addWidget(self.groupBox_3, 3, 2, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_4.setTitle(_fromUtf8(""))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.i_stopBit1_radio = QtGui.QRadioButton(self.groupBox_4)
        self.i_stopBit1_radio.setObjectName(_fromUtf8("i_stopBit1_radio"))
        self.horizontalLayout_3.addWidget(self.i_stopBit1_radio)
        self.i_stopBit15_radio = QtGui.QRadioButton(self.groupBox_4)
        self.i_stopBit15_radio.setObjectName(_fromUtf8("i_stopBit15_radio"))
        self.horizontalLayout_3.addWidget(self.i_stopBit15_radio)
        self.i_stopBit2_radio = QtGui.QRadioButton(self.groupBox_4)
        self.i_stopBit2_radio.setObjectName(_fromUtf8("i_stopBit2_radio"))
        self.horizontalLayout_3.addWidget(self.i_stopBit2_radio)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_3)
        self.gridLayout.addWidget(self.groupBox_4, 4, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lineEdit = QtGui.QLineEdit(Dialog)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout_2.addWidget(self.lineEdit, 4, 2, 1, 1)
        self.label_10 = QtGui.QLabel(Dialog)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 4, 1, 1, 1)
        self.btn_send = QtGui.QPushButton(Dialog)
        self.btn_send.setObjectName(_fromUtf8("btn_send"))
        self.gridLayout_2.addWidget(self.btn_send, 4, 3, 1, 1)
        self.o_recived_plainTextEdit = QtGui.QPlainTextEdit(Dialog)
        self.o_recived_plainTextEdit.setEnabled(True)
        self.o_recived_plainTextEdit.setPlainText(_fromUtf8(""))
        self.o_recived_plainTextEdit.setObjectName(_fromUtf8("o_recived_plainTextEdit"))
        self.gridLayout_2.addWidget(self.o_recived_plainTextEdit, 1, 0, 1, 3)
        self.o_send_plainTextEdit = QtGui.QPlainTextEdit(Dialog)
        self.o_send_plainTextEdit.setObjectName(_fromUtf8("o_send_plainTextEdit"))
        self.gridLayout_2.addWidget(self.o_send_plainTextEdit, 3, 0, 1, 3)
        self.label_9 = QtGui.QLabel(Dialog)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 2, 0, 1, 1)
        self.btn_clear_recived = QtGui.QPushButton(Dialog)
        self.btn_clear_recived.setObjectName(_fromUtf8("btn_clear_recived"))
        self.gridLayout_2.addWidget(self.btn_clear_recived, 1, 3, 1, 1)
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 1)
        self.btn_pingFunction = QtGui.QPushButton(Dialog)
        self.btn_pingFunction.setObjectName(_fromUtf8("btn_pingFunction"))
        self.gridLayout_2.addWidget(self.btn_pingFunction, 4, 0, 1, 1)
        self.btn_clear_send = QtGui.QPushButton(Dialog)
        self.btn_clear_send.setObjectName(_fromUtf8("btn_clear_send"))
        self.gridLayout_2.addWidget(self.btn_clear_send, 2, 3, 2, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.label.setBuddy(self.i_portName_comboBox)
        self.label_5.setBuddy(self.i_stopBit1_radio)
        self.label_3.setBuddy(self.i_word_5bits_radio)
        self.label_2.setBuddy(self.i_baudRate_comboBox)
        self.label_6.setBuddy(self.comboBox_3)
        self.label_7.setBuddy(self.comboBox_4)
        self.label_4.setBuddy(self.i_parityNone_radio)
        self.label_9.setBuddy(self.o_send_plainTextEdit)
        self.label_8.setBuddy(self.o_recived_plainTextEdit)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "IwSK RS-232", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Konfiguracja", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_save.setText(QtGui.QApplication.translate("Dialog", "Zapisz", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_open.setText(QtGui.QApplication.translate("Dialog", "Otwórz port", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_close.setText(QtGui.QApplication.translate("Dialog", "Zamknij port", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Bit stopu:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Długość słowa:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Prędkość transmisji:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Kontrola przepływu:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Terminowanie:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Parzystość:", None, QtGui.QApplication.UnicodeUTF8))
        self.i_word_5bits_radio.setText(QtGui.QApplication.translate("Dialog", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.i_word_6bits_radio.setText(QtGui.QApplication.translate("Dialog", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.i_word_7bits_radio.setText(QtGui.QApplication.translate("Dialog", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.i_word_8bits_radio.setText(QtGui.QApplication.translate("Dialog", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.i_parityNone_radio.setText(QtGui.QApplication.translate("Dialog", "brak", None, QtGui.QApplication.UnicodeUTF8))
        self.i_parityEven_radio.setText(QtGui.QApplication.translate("Dialog", "bit parzystości", None, QtGui.QApplication.UnicodeUTF8))
        self.i_parityOdd_radio.setText(QtGui.QApplication.translate("Dialog", "bit nieparzystości", None, QtGui.QApplication.UnicodeUTF8))
        self.i_stopBit1_radio.setText(QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.i_stopBit15_radio.setText(QtGui.QApplication.translate("Dialog", "1.5", None, QtGui.QApplication.UnicodeUTF8))
        self.i_stopBit2_radio.setText(QtGui.QApplication.translate("Dialog", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "Dane do wysłania:", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_send.setText(QtGui.QApplication.translate("Dialog", "Wyślij", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Dane wysłane:", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_clear_recived.setText(QtGui.QApplication.translate("Dialog", "Wyczyść", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Dane odebrane: ", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_pingFunction.setText(QtGui.QApplication.translate("Dialog", "PING!", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_clear_send.setText(QtGui.QApplication.translate("Dialog", "Wyczyść", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

